set nocompatible
syntax on
filetype on
set number
set relativenumber
set cursorline
set wrap
set showcmd
set wildmenu
set scrolloff=5

set hlsearch
exec "nohlsearch"
set incsearch
set ignorecase
set smartcase
noremap <ESC> :noh<RETURN><ESC>

map s :<nop>
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>

call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'

call plug#end()

" nerd tree"
noremap tt :NERDTreeToggle<CR>
noremap tc :NERDTreeCWD<CR>
noremap tf :NERDTreeFocus<CR>
